### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by garyganyang** [chenyuanchn/cordova-plugin-app-update#1]
:compileDebugJavaWithJavacE:\jianfukeji\drugstore\app\ionic\dispensary\sandbox\demo\myApp-tabs\platforms\android\src\com\cordova\appUpdate\UpdateManager.java:31: ����: ������com.xc.newsmobile������
import com.xc.newsmobile.MainActivity;
                        ^
E:\jianfukeji\drugstore\app\ionic\dispensary\sandbox\demo\myApp-tabs\platforms\android\src\com\cordova\appUpdate\UpdateManager.java:32: ����: ������com.xc.newsmobile������
import com.xc.newsmobile.R;
                        ^
E:\jianfukeji\drugstore\app\ionic\dispensary\sandbox\demo\myApp-tabs\platforms\android\src\com\cordova\appUpdate\UpdateManager.java:152: ����: ������R������
                                        builder1.setSmallIcon(R.drawable.icon); //����ͼ��
                                                               ^
E:\jianfukeji\drugstore\app\ionic\dispensary\sandbox\demo\myApp-tabs\platforms\android\src\com\cordova\appUpdate\UpdateManager.java:432: ����: ������R������
                notification.icon = R.drawable.icon;// ����ͼ������Ҫ���ã���Ȼ�����Ǹ�RemoteViews��������.
                                     ^
E:\jianfukeji\drugstore\app\ionic\dispensary\sandbox\demo\myApp-tabs\platforms\android\src\com\cordova\appUpdate\UpdateManager.java:437: ����: ������R������
                                R.layout.notification_item);
                                 ^
E:\jianfukeji\drugstore\app\ionic\dispensary\sandbox\demo\myApp-tabs\platforms\android\src\com\cordova\appUpdate\UpdateManager.java:438: ����: ������R������
                contentView.setTextViewText(R.id.notificationTitle,
                                             ^
E:\jianfukeji\drugstore\app\ionic\dispensary\sandbox\demo\myApp-tabs\platforms\android\src\com\cordova\appUpdate\UpdateManager.java:440: ����: ������R������
                contentView.setTextViewText(R.id.notificationPercent, "0%");
                                             ^
E:\jianfukeji\drugstore\app\ionic\dispensary\sandbox\demo\myApp-tabs\platforms\android\src\com\cordova\appUpdate\UpdateManager.java:441: ����: ������R������
                contentView.setProgressBar(R.id.notificationProgress, 100, 0, false);
                                            ^
E:\jianfukeji\drugstore\app\ionic\dispensary\sandbox\demo\myApp-tabs\platforms\android\src\com\cordova\appUpdate\UpdateManager.java:450: ����: ������R������
                contentView.setOnClickPendingIntent(R.id.notificationDelete,
                                                     ^
E:\jianfukeji\drugstore\app\ionic\dispensary\sandbox\demo\myApp-tabs\platforms\android\src\com\cordova\appUpdate\UpdateManager.java:455: ����: �Ҳ�������
                updateIntent = new Intent(mContext, MainActivity.class);
                                                    ^
  ����:   �� MainActivity
  λ��: �� UpdateManager
E:\jianfukeji\drugstore\app\ionic\dispensary\sandbox\demo\myApp-tabs\platforms\android\src\com\cordova\appUpdate\UpdateManager.java:526: ����: ������R������
                                                        contentView.setTextViewText(R.id.notificationPercent,
                                                                                     ^
E:\jianfukeji\drugstore\app\ionic\dispensary\sandbox\demo\myApp-tabs\platforms\android\src\com\cordova\appUpdate\UpdateManager.java:528: ����: ������R������
                                                        contentView.setProgressBar(R.id.notificationProgress,
                                                                                    ^
ע: ĳЩ�����ļ�ʹ�û�����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
12 ������

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':compileDebugJavaWithJavac'.
  
  > Compilation failed; see the compiler error output for details.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
  FAILED

BUILD FAILED

Total time: 2.685 secs

**Comment by chenyuanchn** [comment]
安装时如果报错，应该是
安装完毕后修改UpdateManager的import com.xc.newsmobile.MainActivity;import com.xc.newsmobile.R; 包名改为自己项目路径
这个问题，我暂时还不知道如何让这些路径可以自适应安装者的项目对应的包路径

------------------ 原始邮件 ------------------
发件人: "甘杨";notifications@github.com;
发送时间: 2016年6月13日(星期一) 上午9:54
收件人: "chenyuanchn/cordova-plugin-app-update"cordova-plugin-app-update@noreply.github.com; 

主题: Re: [chenyuanchn/cordova-plugin-app-update] FAILURE: Build failedwith an exception. (#1)

Closed #1.
