### ISSUE TITLE
为什么要注释很多代码呢?

### ISSUE THREAD

**Issue by garyganyang** [chenyuanchn/cordova-plugin-app-update#2]
在UpdateManager.java里面, 为什么要注释很多代码呢?是还不稳定还是怎么回事呢?
还有一些不必要的log是否可以在发布版本中都去掉呢?

**Comment by chenyuanchn** [comment]
注释和log都能删除，希望您能一起帮忙完善这个插件，例如：通知栏提示进度条还是直接在页面上显示，是否下载完自动安装，都是可以弄成可配置，并且该插件还有很多bug需要修复

------------------ 原始邮件 ------------------
发件人: "甘杨";notifications@github.com;
发送时间: 2016年6月13日(星期一) 中午1:56
收件人: "chenyuanchn/cordova-plugin-app-update"cordova-plugin-app-update@noreply.github.com; 

主题: [chenyuanchn/cordova-plugin-app-update] 为什么要注释很多代码呢? (#2)

在UpdateManager.java里面, 为什么要注释很多代码呢?是还不稳定还是怎么回事呢?
 还有一些不必要的log是否可以在发布版本中都去掉呢?
